### ISSUE TITLE
Livrée Dites33

### ISSUE THREAD

**Issue by Dites33** [Dites33/AA#1]
Le dégradé sur les boutton (FD, LS, APPR, etc) s'il rend très bien en très gros plan, ça donne un effet un peu de flou à la lumière du bouton

**Comment by Dites33** [comment]
Correction disponible, à tester

**Comment by Fixoutor** [comment]
TEST OK.
Par contre on peut voir un léger trait blanc sur la couleur rouge.
![20210429215925_1](https://user-images.githubusercontent.com/11321547/116611145-52f44380-a936-11eb-8706-08e6021d8313.jpg)

**Comment by Dites33** [comment]
Correction disponible, à tester

**Comment by Fixoutor** [comment]
TEST OK, par contre, plus de couleur "arc en ciel" mais blanc. Normal ?
![20210501221844_1](https://user-images.githubusercontent.com/11321547/116794150-3e957f80-aacb-11eb-86aa-c52a798fe219.jpg)
