### ISSUE TITLE
Livrée ADIBOU- [Amélioration] Changement de couleur pour les boutons ON/OFF 

### ISSUE THREAD

**Issue by Fixoutor** [Dites33/AA#10]
Je pense qu'il faudrait pourvoir distinguer les boutons OFF des boutons ON. Car ici tout est blanc. Etant donnée que le code couleur d'un bouton OFF est "blanc", il serait préférable de changer la couleur du ON. Par exemple le "vert" de la livrée.
![20210426233924_1](https://user-images.githubusercontent.com/11321547/116381500-3f04f080-a815-11eb-9dfb-8bb0907567e2.jpg)

**Comment by Dites33** [comment]
Correction disponible, à tester

**Comment by Fixoutor** [comment]
TEST OK !
