### ISSUE TITLE
Livrée ADIBOU - Pixellisation 

### ISSUE THREAD

**Issue by Fixoutor** [Dites33/AA#12]
![20210426234423_1](https://user-images.githubusercontent.com/11321547/116389807-ad4db100-a81d-11eb-9df0-bf5b1fafbb7b.jpg)
![20210426234552_1](https://user-images.githubusercontent.com/11321547/116389812-ade64780-a81d-11eb-80b5-a5aeb3f9469a.jpg)

**Comment by Dites33** [comment]
Correction disponible, à tester

**Comment by Fixoutor** [comment]
TEST OK
