### ISSUE TITLE
Livrée LUKE - Coloration différente 

### ISSUE THREAD

**Issue by Fixoutor** [Dites33/AA#13]
Nous avons deux colorations différente, d'un coté (gauche) l'imitation capitonnage. de l'autre simple couleur rose.

![20210426235719_1](https://user-images.githubusercontent.com/11321547/116395717-c443d180-a824-11eb-8449-8865d9e98dce.jpg)
![20210426235724_1](https://user-images.githubusercontent.com/11321547/116395718-c4dc6800-a824-11eb-887a-04152d2de96d.jpg)

**Comment by Dites33** [comment]
Correction disponible, à tester

**Comment by Fixoutor** [comment]
TEST OK
