### ISSUE TITLE
Livrée ADIBOU - Rétroéclairage

### ISSUE THREAD

**Issue by Fixoutor** [Dites33/AA#14]
Dans cette livrée, la couleur blanche est aveuglante, notamment à 100%, ce qui "cache" les instruments.
Changer cette couleur par un gris (ou blanc avec plus de contraste) ?

![20210427001235_1](https://user-images.githubusercontent.com/11321547/116395979-14bb2f00-a825-11eb-860e-db601777d761.jpg)

**Comment by Dites33** [comment]
Correction disponible, à tester

**Comment by Fixoutor** [comment]
TEST OK
