### ISSUE TITLE
Toutes les livrées (Sauf DITES33) - [Amélioration] - Personnalisation de la boucle de ceinture

### ISSUE THREAD

**Issue by Fixoutor** [Dites33/AA#15]
Pour une personnalisation plus poussée, serait-il possible de changer le DITES33 dans la boucle, par ADIBOU / AZHGAAAR / LUKI / etc... ?

![20210426234046_1](https://user-images.githubusercontent.com/11321547/116396513-c8bcba00-a825-11eb-875b-7fe11ad9a66d.jpg)

**Comment by Dites33** [comment]
Je comprends mieux avec ton autre demande, je regarde ce que je peux faire.

**Comment by Fixoutor** [comment]
TEST OK
