### ISSUE TITLE
Toutes livrées - [Amélioration] - Signature du créateur

### ISSUE THREAD

**Issue by Fixoutor** [Dites33/AA#18]
Il serai fort appréciable d'avoir une "étiquette" ou gravure du créateur de la livrée.
Exemple sur les appuis têtes ou le coté des sièges avec le texte : 

**Generated by DITES33**

![20210427000018_1](https://user-images.githubusercontent.com/11321547/116398790-7a5cea80-a828-11eb-9aed-3194e484a6b7.jpg)
![20210427000221_1](https://user-images.githubusercontent.com/11321547/116398795-7b8e1780-a828-11eb-9923-453833903f4d.jpg)

**Comment by Dites33** [comment]
Merci pour cette idée :) Tu as déjà le nom sur la boucle de ceinture sur l'assise du fauteuil :)

**Comment by Dites33** [comment]
En réflexion par rapport au ticket sur la boucle

**Comment by Dites33** [comment]
Credits mis sur le tableau de bord avec les greetings. Sera bougé si un instrument vient prendre place ici un jour ...

**Comment by Fixoutor** [comment]
TEST OK !
