### ISSUE TITLE
Livrée DITES33 et Mr Pepe  - Amélioration bouton overhead

### ISSUE THREAD

**Issue by Lykimaia** [Dites33/AA#19]
![image](https://user-images.githubusercontent.com/83336657/116460721-a64b9080-a867-11eb-88f8-0d8f017c9df9.png)
Sur les boutons de l'overhead, allumé certain ne sont pas lisible

**Comment by Dites33** [comment]
Correction disponible, à tester

**Comment by Dites33** [comment]
Correction disponible, à tester

**Comment by Fixoutor** [comment]
TEST OK
