### ISSUE TITLE
Livrée : Adibou, Azghaaar, Dites33, Mr Pepe,  Pas d'affichage pour Master Caution et Master Warning

### ISSUE THREAD

**Issue by Lykimaia** [Dites33/AA#20]
![image](https://user-images.githubusercontent.com/83336657/116461762-ef501480-a868-11eb-8e02-d41ad20a54d5.png)
Les boutons n'ont pas d'affichage alors que je suis en bien en rouge sur l'ECAM et même lors du test de light

**Comment by Dites33** [comment]
En version dev j'ai le même problème sur la livrée de base Asobo Bleu et blanche A320Neo avec l'A32NX , peux tu vérifier ?

**Comment by Lykimaia** [comment]
Celle-ci : ? 
![image](https://user-images.githubusercontent.com/83336657/116463946-9fbf1800-a86b-11eb-806f-3a8a986f13bb.png)
Si oui j'ai bien les boutons en version DEV Fbw32nx
![image](https://user-images.githubusercontent.com/83336657/116463907-946bec80-a86b-11eb-8579-0d4ab825f2f1.png)

**Comment by Fixoutor** [comment]
OK
