### ISSUE TITLE
Livrée Twenty - Aileron

### ISSUE THREAD

**Issue by Dhouly95200** [Dites33/AA#21]
Je sais pas si c'est normal mais il y a une partie blanche au niveau de l'aileron de l'A320 livrée Twenty, sur les deux côtés #
![Image aileron arièrre livrée Twenty](https://user-images.githubusercontent.com/83337770/116515539-b8134f00-a8cc-11eb-9cba-d1cc16ce9e4c.PNG)

**Comment by Dites33** [comment]
C'est normal, c'est la partie ou 'tourne' l'aileron arrière droite et gauche. 
Pour l'instant je ne sais pas la peindre
