### ISSUE TITLE
Livrée LYKI

### ISSUE THREAD

**Issue by Lykimaia** [Dites33/AA#23]
Un petit manque de peinture sous l'avion : 
![image](https://user-images.githubusercontent.com/83336657/117619662-d5b7a280-b16f-11eb-94dd-59f4e12886a5.png)

**Comment by Dites33** [comment]
Hum ...

Coté model 3d je suis pile au bon endroit. Compliqué si c'st un défaut du modele :(

![image](https://user-images.githubusercontent.com/14044648/117625506-61343200-b176-11eb-9945-2f714c2f881b.png)

**Comment by Lykimaia** [comment]
Après je vole pas en regardant le dessous de l'avion :p

**Comment by Dites33** [comment]
Ha ? :D
