### ISSUE TITLE
Livrée Azghaaar - Pixelisation

### ISSUE THREAD

**Issue by Dites33** [Dites33/AA#3]
Mode Ultra - Carte graphique P5000 Nvidia

![image](https://user-images.githubusercontent.com/14044648/116366769-efb7c380-a806-11eb-8ab6-b26a72d7624c.png)

![image](https://user-images.githubusercontent.com/14044648/116366885-0b22ce80-a807-11eb-9463-fc7c299b0180.png)

![image](https://user-images.githubusercontent.com/14044648/116366956-2097f880-a807-11eb-8389-8cabb47d8c9e.png)

**Comment by Dites33** [comment]
Livrée refaite à zéro. A vérifier

**Comment by Fixoutor** [comment]
TEST OK
