### ISSUE TITLE
Livrée Twenty - Problème sur alarmes

### ISSUE THREAD

**Issue by Dites33** [Dites33/AA#4]
![image](https://user-images.githubusercontent.com/14044648/116367213-65239400-a807-11eb-9bfd-dac79ce068fb.png)

**Comment by Lykimaia** [comment]
Idem sur la livrée de Mr Pepe
![image](https://user-images.githubusercontent.com/83336657/116461301-5faa6600-a868-11eb-956c-9ac3460d749a.png)

**Comment by Lykimaia** [comment]
Idem sur la livrée Luke 
![image](https://user-images.githubusercontent.com/83336657/116461376-7781ea00-a868-11eb-8b1f-bd0b52b08850.png)
