### ISSUE TITLE
Livrée Twenty - Problème sous réservoir

### ISSUE THREAD

**Issue by Dites33** [Dites33/AA#5]
![image](https://user-images.githubusercontent.com/14044648/116367265-740a4680-a807-11eb-9ca0-5c8b04f7271d.png)
![image](https://user-images.githubusercontent.com/14044648/116367295-7cfb1800-a807-11eb-8c61-d800b47640cf.png)
![image](https://user-images.githubusercontent.com/14044648/116367307-81273580-a807-11eb-9350-26b7ab916d12.png)
![image](https://user-images.githubusercontent.com/14044648/116367429-a4ea7b80-a807-11eb-9579-c52c4fd6e7fa.png)

**Comment by Fixoutor** [comment]
TEST OK
